import { NextRequest, NextResponse } from 'next/server';
import { google } from 'googleapis';
import { apiError, requireEnv, parseBody, corsHeaders, EnvMissingError } from '@/lib/api-helpers';

interface ConceptData {
  title: string;
  format: string;
  hook: string;
  insight: string;
  structure: string;
  whyWins: string;
}

interface SaveDocBody {
  concepts?: ConceptData[];
  analysis?: string;
  transcriptCount?: number;
}

export async function POST(request: NextRequest) {
  try {
    const { concepts = [], analysis = '', transcriptCount = 0 } = await parseBody<SaveDocBody>(request);
    const email = requireEnv('GOOGLE_SERVICE_ACCOUNT_EMAIL');
    const keyRaw = requireEnv('GOOGLE_PRIVATE_KEY');
    const folderId = process.env.GOOGLE_DRIVE_FOLDER_ID || '';

    const privateKey = keyRaw.replace(/\\n/g, '\n');

    const auth = new google.auth.JWT({
      email,
      key: privateKey,
      scopes: [
        'https://www.googleapis.com/auth/documents',
        'https://www.googleapis.com/auth/drive',
      ],
    });

    const docs = google.docs({ version: 'v1', auth });
    const drive = google.drive({ version: 'v3', auth });

    // Build doc title
    const now = new Date();
    const title = `Content Brief — ${now.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`;

    // Create blank doc directly in target folder
    const fileMetadata: any = {
      name: title,
      mimeType: 'application/vnd.google-apps.document',
    };
    if (folderId) {
      fileMetadata.parents = [folderId];
    }

    const createRes = await drive.files.create({
      requestBody: fileMetadata,
      supportsAllDrives: true,
      fields: 'id'
    });
    const docId = createRes.data.id!;

    // Build doc content as batchUpdate requests
    const dateStr = now.toLocaleDateString('en-GB', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const lines: { text: string; style: string | null }[] = [
      { text: 'CONTENT INTELLIGENCE ENGINE\n', style: 'TITLE' },
      { text: `${dateStr}  ·  ${transcriptCount} videos analyzed\n`, style: 'SUBTITLE' },
      { text: '\n', style: null },
      { text: 'SECTION 1 — COMPETITIVE INTELLIGENCE\n', style: 'HEADING_1' },
      { text: '\n', style: null },
      { text: analysis + '\n', style: 'NORMAL_TEXT' },
      { text: '\n', style: null },
      {
        text: `SECTION 2 — VIDEO CONCEPTS (${now.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })})\n`,
        style: 'HEADING_1',
      },
      { text: '\n', style: null },
    ];

    concepts.forEach((c, i) => {
      lines.push({ text: `${i + 1}. ${c.title}\n`, style: 'HEADING_2' });
      lines.push({ text: `Format: ${c.format}\n`, style: 'NORMAL_TEXT' });
      lines.push({ text: `Hook: "${c.hook}"\n`, style: 'NORMAL_TEXT' });
      lines.push({ text: `Core Insight: ${c.insight}\n`, style: 'NORMAL_TEXT' });
      lines.push({ text: `Structure: ${c.structure}\n`, style: 'NORMAL_TEXT' });
      lines.push({ text: `Why It Wins: ${c.whyWins}\n`, style: 'NORMAL_TEXT' });
      lines.push({ text: '\n', style: null });
    });

    lines.push({
      text: `Generated by Content Intelligence Engine · ${dateStr}\n`,
      style: 'NORMAL_TEXT',
    });

    // Insert all text & apply styles
    const fullText = lines.map((l) => l.text).join('');
    const requests: object[] = [{ insertText: { location: { index: 1 }, text: fullText } }];

    let index = 1;
    for (const line of lines) {
      const len = line.text.length;
      if (line.style) {
        requests.push({
          updateParagraphStyle: {
            range: { startIndex: index, endIndex: index + len },
            paragraphStyle: { namedStyleType: line.style },
            fields: 'namedStyleType',
          },
        });
      }
      index += len;
    }

    await docs.documents.batchUpdate({
      documentId: docId,
      requestBody: { requests },
    });

    const docUrl = `https://docs.google.com/document/d/${docId}/edit`;
    return NextResponse.json({ docUrl, docId, title }, { headers: corsHeaders });
  } catch (e) {
    if (e instanceof EnvMissingError) return apiError(e.message, 500);
    return apiError((e as Error).message, 500);
  }
}

export const maxDuration = 60;
