/**
 * Video Downloader using yt-dlp
 * Downloads Instagram Reels/posts as local mp4 files via child_process.
 * Uses Playwright-exported cookies for Instagram authentication.
 */
import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';

export interface DownloadedItem {
  videoUrl: string;
  pageUrl: string;
  localPath: string | null;
  account: string;
  views: number;
  likes: number;
  caption: string;
  source: string;
  error?: string;
}

function randomDelay(min = 2000, max = 4000): Promise<void> {
  const ms = Math.floor(Math.random() * (max - min)) + min;
  return new Promise((r) => setTimeout(r, ms));
}

function sanitizeFilename(url: string, index: number): string {
  const match = url.match(/\/(reel|reels|p)\/([\w-]+)/);
  const id = match ? match[2] : `video_${index}`;
  return id.replace(/[^a-zA-Z0-9_-]/g, '_');
}

/**
 * Check if yt-dlp is available on the system
 */
export async function checkYtDlp(): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn('yt-dlp', ['--version'], { windowsHide: true });
    proc.on('error', () => resolve(false));
    proc.on('close', (code) => resolve(code === 0));
  });
}

/**
 * Convert Playwright cookies (JSON) to Netscape cookie format for yt-dlp.
 * Returns path to the generated cookies.txt file, or null if no cookies exist.
 */
function getNetscapeCookiesPath(): string | null {
  const playwrightCookies = path.join(process.cwd(), 'data', 'cookies.json');
  const netscapeCookies = path.join(process.cwd(), 'data', 'cookies.txt');

  if (!fs.existsSync(playwrightCookies)) return null;

  try {
    const raw = fs.readFileSync(playwrightCookies, 'utf-8');
    const cookies = JSON.parse(raw);
    if (!Array.isArray(cookies) || cookies.length === 0) return null;

    // Netscape cookie file format header
    let output = '# Netscape HTTP Cookie File\n# Generated by Content Intelligence Engine\n\n';

    for (const c of cookies) {
      const domain = c.domain || '.instagram.com';
      const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const cookiePath = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const expires = c.expires ? Math.round(c.expires) : '0';
      const name = c.name || '';
      const value = c.value || '';

      output += `${domain}\t${flag}\t${cookiePath}\t${secure}\t${expires}\t${name}\t${value}\n`;
    }

    fs.writeFileSync(netscapeCookies, output);
    return netscapeCookies;
  } catch {
    return null;
  }
}

/**
 * Download a single video using yt-dlp.
 * Uses output TEMPLATE (not fixed name) to avoid the "more than one file" error.
 * Uses Netscape cookie file for Instagram authentication.
 */
function downloadSingle(
  url: string,
  downloadDir: string,
  desiredName: string,
  cookiesPath: string | null,
  log: (msg: string) => void,
): Promise<string | null> {
  return new Promise((resolve) => {
    const desiredPath = path.join(downloadDir, `${desiredName}.mp4`);

    // If already exists, skip
    if (fs.existsSync(desiredPath)) {
      resolve(desiredPath);
      return;
    }

    // Use output template — yt-dlp chooses the filename based on video ID
    const outputTemplate = path.join(downloadDir, `${desiredName}_%(id)s.%(ext)s`);

    const args = [
      '--no-playlist',
      '--playlist-items', '1',
      '-f', 'b',                         // Best single format (suppresses warning)
      '--no-check-certificates',
      '--no-warnings',
      '--no-write-thumbnail',
      '--no-write-info-json',
      '--no-write-comments',
      '--no-overwrites',
      '-o', outputTemplate,
    ];

    // Add cookie authentication if available
    if (cookiesPath) {
      args.push('--cookies', cookiesPath);
    }

    args.push(url);

    // Spawn yt-dlp directly (no shell) — avoids both:
    //   • PowerShell mangling %(id)s template variables
    //   • cmd.exe quoting issues with spaces in paths
    // Node's CreateProcess on Windows handles arg escaping properly.
    const proc = spawn('yt-dlp', args, {
      timeout: 120000,
      windowsHide: true,
    });

    let stderr = '';
    let stdout = '';

    proc.stdout?.on('data', (data: Buffer) => {
      const line = data.toString().trim();
      stdout += line + '\n';
      const pctMatch = line.match(/(\d+\.?\d*)%/);
      if (pctMatch) {
        const pct = parseFloat(pctMatch[1]);
        if (pct >= 99 || pct % 25 < 5) {
          log(`  ↓ ${Math.round(pct)}%`);
        }
      }
    });

    proc.stderr?.on('data', (data: Buffer) => {
      stderr += data.toString();
    });

    proc.on('close', async (code) => {
      if (code === 0) {
        // Find the downloaded file — look for our prefix in the directory
        const files = fs.readdirSync(downloadDir)
          .filter((f) => f.startsWith(desiredName) && !f.endsWith('.part'))
          .map((f) => ({
            name: f,
            fullPath: path.join(downloadDir, f),
            time: fs.statSync(path.join(downloadDir, f)).mtimeMs,
          }))
          .sort((a, b) => b.time - a.time);

        if (files.length > 0) {
          const downloadedFile = files[0].fullPath;
          if (downloadedFile !== desiredPath) {
            try { fs.renameSync(downloadedFile, desiredPath); } catch {
              resolve(downloadedFile);
              return;
            }
          }
          resolve(desiredPath);
        } else {
          log(`  ✗ yt-dlp exited OK but no file found`);
          resolve(null);
        }
      } else {
        const errMsg = (stderr.trim() || stdout.trim()).split('\n').pop() || '';
        log(`  ✗ yt-dlp native block detected. Handing off to Cobalt API fallback proxy…`);
        
        // Auto-heal cookies
        if (errMsg.includes('login required') || errMsg.includes('rate-limit reached') || errMsg.includes('Use --cookies')) {
          try {
            const dataDir = path.join(process.cwd(), 'data');
            if (cookiesPath && fs.existsSync(cookiesPath)) fs.unlinkSync(cookiesPath);
            if (fs.existsSync(path.join(dataDir, 'cookies.json'))) fs.unlinkSync(path.join(dataDir, 'cookies.json'));
          } catch {}
        }
        
        // Fallback to Cobalt API (Free, open-source downloader that bypasses IP blocks)
        try {
          const cobaltResponse = await fetch('https://api.cobalt.tools/api/json', {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              url: url,
              vQuality: '720'
            })
          });

          const cobaltData = await cobaltResponse.json();
          if (cobaltData && cobaltData.url) {
            log(`  ✓ Cobalt API success! Downloading file stream…`);
            
            // Download the direct file stream provided by Cobalt
            const streamRes = await fetch(cobaltData.url);
            const arrayBuffer = await streamRes.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            
            fs.writeFileSync(desiredPath, buffer);
            log(`  ✓ Fallback download successful (Cobalt)`);
            resolve(desiredPath);
            return;
          }
        } catch (fallErr) {
          log(`  ✗ Cobalt fallback also failed: ${(fallErr as Error).message}`);
        }

        resolve(null);
      }
    });

    proc.on('error', (err) => {
      log(`  ✗ yt-dlp spawn error: ${err.message}`);
      resolve(null);
    });
  });
}

/**
 * Download all videos sequentially
 */
export async function download(
  videos: Array<{ videoUrl: string; pageUrl: string; account: string; views: number; likes: number; caption: string; source: string }>,
  runId: string,
  log: (msg: string) => void,
): Promise<DownloadedItem[]> {
  const available = await checkYtDlp();
  if (!available) {
    throw new Error('yt-dlp is not installed. Install it with: pip install yt-dlp');
  }

  const downloadDir = path.join(process.cwd(), 'data', 'downloads', runId);
  if (!fs.existsSync(downloadDir)) {
    fs.mkdirSync(downloadDir, { recursive: true });
  }

  // Convert Playwright cookies → Netscape format for yt-dlp auth
  const cookiesPath = getNetscapeCookiesPath();
  if (cookiesPath) {
    log('Using saved Instagram cookies for authentication');
  } else {
    log('No cookies found — downloads may fail if Instagram requires login');
  }

  const results: DownloadedItem[] = [];

  for (let i = 0; i < videos.length; i++) {
    const video = videos[i];
    const filename = sanitizeFilename(video.pageUrl || video.videoUrl, i);

    log(`Downloading ${i + 1}/${videos.length}: @${video.account}…`);

    const localPath = await downloadSingle(
      video.pageUrl || video.videoUrl,
      downloadDir,
      filename,
      cookiesPath,
      log,
    );

    if (localPath) {
      log(`  ✓ Downloaded`);
    }

    results.push({
      ...video,
      localPath,
      error: localPath ? undefined : 'Download failed',
    });

    if (i < videos.length - 1) {
      await randomDelay(2000, 4000);
    }
  }

  const successful = results.filter((r) => r.localPath);
  log(`Downloads complete: ${successful.length}/${videos.length} succeeded`);

  return results;
}
